"".add STEXT nosplit size=19 args=0x18 locals=0x0
	0x0000 00000 (x.go:5)	TEXT	"".add(SB), NOSPLIT, $0-24
	0x0000 00000 (x.go:5)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (x.go:5)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (x.go:5)	FUNCDATA	$3, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x0000 00000 (x.go:6)	PCDATA	$2, $0
	0x0000 00000 (x.go:6)	PCDATA	$0, $0
	0x0000 00000 (x.go:6)	MOVQ	"".b+16(SP), AX
	0x0005 00005 (x.go:6)	MOVQ	"".a+8(SP), CX
	0x000a 00010 (x.go:6)	ADDQ	CX, AX
	0x000d 00013 (x.go:6)	MOVQ	AX, "".~r2+24(SP)
	0x0012 00018 (x.go:6)	RET
	0x0000 48 8b 44 24 10 48 8b 4c 24 08 48 01 c8 48 89 44  H.D$.H.L$.H..H.D
	0x0010 24 18 c3                                         $..
"".main STEXT size=202 args=0x0 locals=0x58
	0x0000 00000 (x.go:8)	TEXT	"".main(SB), $88-0
	0x0000 00000 (x.go:8)	MOVQ	(TLS), CX
	0x0009 00009 (x.go:8)	CMPQ	SP, 16(CX)
	0x000d 00013 (x.go:8)	JLS	192
	0x0013 00019 (x.go:8)	SUBQ	$88, SP
	0x0017 00023 (x.go:8)	MOVQ	BP, 80(SP)
	0x001c 00028 (x.go:8)	LEAQ	80(SP), BP
	0x0021 00033 (x.go:8)	FUNCDATA	$0, gclocals·7d2d5fca80364273fb07d5820a76fef4(SB)
	0x0021 00033 (x.go:8)	FUNCDATA	$1, gclocals·ef22736e31ca7e9ff10587cea75d17ff(SB)
	0x0021 00033 (x.go:8)	FUNCDATA	$3, gclocals·1cf923758aae2e428391d1783fe59973(SB)
	0x0021 00033 (x.go:9)	PCDATA	$2, $0
	0x0021 00033 (x.go:9)	PCDATA	$0, $1
	0x0021 00033 (x.go:9)	XORPS	X0, X0
	0x0024 00036 (x.go:9)	MOVUPS	X0, ""..autotmp_3+64(SP)
	0x0029 00041 (x.go:9)	PCDATA	$2, $1
	0x0029 00041 (x.go:9)	LEAQ	type.int(SB), AX
	0x0030 00048 (x.go:9)	PCDATA	$2, $0
	0x0030 00048 (x.go:9)	MOVQ	AX, ""..autotmp_3+64(SP)
	0x0035 00053 (x.go:9)	PCDATA	$2, $2
	0x0035 00053 (x.go:9)	LEAQ	"".statictmp_0(SB), CX
	0x003c 00060 (x.go:9)	PCDATA	$2, $0
	0x003c 00060 (x.go:9)	MOVQ	CX, ""..autotmp_3+72(SP)
	0x0041 00065 (x.go:9)	PCDATA	$2, $2
	0x0041 00065 (x.go:9)	LEAQ	""..autotmp_3+64(SP), CX
	0x0046 00070 (x.go:9)	PCDATA	$2, $0
	0x0046 00070 (x.go:9)	MOVQ	CX, (SP)
	0x004a 00074 (x.go:9)	MOVQ	$1, 8(SP)
	0x0053 00083 (x.go:9)	MOVQ	$1, 16(SP)
	0x005c 00092 (x.go:9)	CALL	fmt.Println(SB)
	0x0061 00097 (x.go:10)	PCDATA	$0, $2
	0x0061 00097 (x.go:10)	XORPS	X0, X0
	0x0064 00100 (x.go:10)	MOVUPS	X0, ""..autotmp_4+48(SP)
	0x0069 00105 (x.go:10)	PCDATA	$2, $1
	0x0069 00105 (x.go:10)	LEAQ	type.int(SB), AX
	0x0070 00112 (x.go:10)	PCDATA	$2, $0
	0x0070 00112 (x.go:10)	MOVQ	AX, (SP)
	0x0074 00116 (x.go:10)	MOVQ	$3, 8(SP)
	0x007d 00125 (x.go:10)	CALL	runtime.convT2E64(SB)
	0x0082 00130 (x.go:10)	MOVQ	16(SP), AX
	0x0087 00135 (x.go:10)	PCDATA	$2, $2
	0x0087 00135 (x.go:10)	MOVQ	24(SP), CX
	0x008c 00140 (x.go:10)	MOVQ	AX, ""..autotmp_4+48(SP)
	0x0091 00145 (x.go:10)	PCDATA	$2, $0
	0x0091 00145 (x.go:10)	MOVQ	CX, ""..autotmp_4+56(SP)
	0x0096 00150 (x.go:10)	PCDATA	$2, $1
	0x0096 00150 (x.go:10)	LEAQ	""..autotmp_4+48(SP), AX
	0x009b 00155 (x.go:10)	PCDATA	$2, $0
	0x009b 00155 (x.go:10)	MOVQ	AX, (SP)
	0x009f 00159 (x.go:10)	MOVQ	$1, 8(SP)
	0x00a8 00168 (x.go:10)	MOVQ	$1, 16(SP)
	0x00b1 00177 (x.go:10)	CALL	fmt.Println(SB)
	0x00b6 00182 (x.go:11)	PCDATA	$0, $0
	0x00b6 00182 (x.go:11)	MOVQ	80(SP), BP
	0x00bb 00187 (x.go:11)	ADDQ	$88, SP
	0x00bf 00191 (x.go:11)	RET
	0x00c0 00192 (x.go:11)	NOP
	0x00c0 00192 (x.go:8)	PCDATA	$0, $-1
	0x00c0 00192 (x.go:8)	PCDATA	$2, $-1
	0x00c0 00192 (x.go:8)	CALL	runtime.morestack_noctxt(SB)
	0x00c5 00197 (x.go:8)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 ad  eH..%....H;a....
	0x0010 00 00 00 48 83 ec 58 48 89 6c 24 50 48 8d 6c 24  ...H..XH.l$PH.l$
	0x0020 50 0f 57 c0 0f 11 44 24 40 48 8d 05 00 00 00 00  P.W...D$@H......
	0x0030 48 89 44 24 40 48 8d 0d 00 00 00 00 48 89 4c 24  H.D$@H......H.L$
	0x0040 48 48 8d 4c 24 40 48 89 0c 24 48 c7 44 24 08 01  HH.L$@H..$H.D$..
	0x0050 00 00 00 48 c7 44 24 10 01 00 00 00 e8 00 00 00  ...H.D$.........
	0x0060 00 0f 57 c0 0f 11 44 24 30 48 8d 05 00 00 00 00  ..W...D$0H......
	0x0070 48 89 04 24 48 c7 44 24 08 03 00 00 00 e8 00 00  H..$H.D$........
	0x0080 00 00 48 8b 44 24 10 48 8b 4c 24 18 48 89 44 24  ..H.D$.H.L$.H.D$
	0x0090 30 48 89 4c 24 38 48 8d 44 24 30 48 89 04 24 48  0H.L$8H.D$0H..$H
	0x00a0 c7 44 24 08 01 00 00 00 48 c7 44 24 10 01 00 00  .D$.....H.D$....
	0x00b0 00 e8 00 00 00 00 48 8b 6c 24 50 48 83 c4 58 c3  ......H.l$PH..X.
	0x00c0 e8 00 00 00 00 e9 36 ff ff ff                    ......6...
	rel 5+4 t=16 TLS+0
	rel 44+4 t=15 type.int+0
	rel 56+4 t=15 "".statictmp_0+0
	rel 93+4 t=8 fmt.Println+0
	rel 108+4 t=15 type.int+0
	rel 126+4 t=8 runtime.convT2E64+0
	rel 178+4 t=8 fmt.Println+0
	rel 193+4 t=8 runtime.morestack_noctxt+0
"".init STEXT size=92 args=0x0 locals=0x8
	0x0000 00000 (<autogenerated>:1)	TEXT	"".init(SB), $8-0
	0x0000 00000 (<autogenerated>:1)	MOVQ	(TLS), CX
	0x0009 00009 (<autogenerated>:1)	CMPQ	SP, 16(CX)
	0x000d 00013 (<autogenerated>:1)	JLS	85
	0x000f 00015 (<autogenerated>:1)	SUBQ	$8, SP
	0x0013 00019 (<autogenerated>:1)	MOVQ	BP, (SP)
	0x0017 00023 (<autogenerated>:1)	LEAQ	(SP), BP
	0x001b 00027 (<autogenerated>:1)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001b 00027 (<autogenerated>:1)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001b 00027 (<autogenerated>:1)	FUNCDATA	$3, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001b 00027 (<autogenerated>:1)	PCDATA	$2, $0
	0x001b 00027 (<autogenerated>:1)	PCDATA	$0, $0
	0x001b 00027 (<autogenerated>:1)	MOVBLZX	"".initdone·(SB), AX
	0x0022 00034 (<autogenerated>:1)	CMPB	AL, $1
	0x0025 00037 (<autogenerated>:1)	JLS	48
	0x0027 00039 (<autogenerated>:1)	PCDATA	$2, $-2
	0x0027 00039 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0027 00039 (<autogenerated>:1)	MOVQ	(SP), BP
	0x002b 00043 (<autogenerated>:1)	ADDQ	$8, SP
	0x002f 00047 (<autogenerated>:1)	RET
	0x0030 00048 (<autogenerated>:1)	JNE	57
	0x0032 00050 (<autogenerated>:1)	PCDATA	$2, $0
	0x0032 00050 (<autogenerated>:1)	PCDATA	$0, $0
	0x0032 00050 (<autogenerated>:1)	CALL	runtime.throwinit(SB)
	0x0037 00055 (<autogenerated>:1)	UNDEF
	0x0039 00057 (<autogenerated>:1)	MOVB	$1, "".initdone·(SB)
	0x0040 00064 (<autogenerated>:1)	CALL	fmt.init(SB)
	0x0045 00069 (<autogenerated>:1)	MOVB	$2, "".initdone·(SB)
	0x004c 00076 (<autogenerated>:1)	MOVQ	(SP), BP
	0x0050 00080 (<autogenerated>:1)	ADDQ	$8, SP
	0x0054 00084 (<autogenerated>:1)	RET
	0x0055 00085 (<autogenerated>:1)	NOP
	0x0055 00085 (<autogenerated>:1)	PCDATA	$0, $-1
	0x0055 00085 (<autogenerated>:1)	PCDATA	$2, $-1
	0x0055 00085 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x005a 00090 (<autogenerated>:1)	JMP	0
	0x0000 65 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 46 48  eH..%....H;a.vFH
	0x0010 83 ec 08 48 89 2c 24 48 8d 2c 24 0f b6 05 00 00  ...H.,$H.,$.....
	0x0020 00 00 80 f8 01 76 09 48 8b 2c 24 48 83 c4 08 c3  .....v.H.,$H....
	0x0030 75 07 e8 00 00 00 00 0f 0b c6 05 00 00 00 00 01  u...............
	0x0040 e8 00 00 00 00 c6 05 00 00 00 00 02 48 8b 2c 24  ............H.,$
	0x0050 48 83 c4 08 c3 e8 00 00 00 00 eb a4              H...........
	rel 5+4 t=16 TLS+0
	rel 30+4 t=15 "".initdone·+0
	rel 51+4 t=8 runtime.throwinit+0
	rel 59+4 t=15 "".initdone·+-1
	rel 65+4 t=8 fmt.init+0
	rel 71+4 t=15 "".initdone·+-1
	rel 86+4 t=8 runtime.morestack_noctxt+0
go.info."".add$abstract SDWARFINFO dupok size=25
	0x0000 03 2e 61 64 64 00 01 01 10 61 00 00 00 00 00 00  ..add....a......
	0x0010 10 62 00 00 00 00 00 00 00                       .b.......
	rel 12+4 t=28 go.info.int+0
	rel 20+4 t=28 go.info.int+0
go.loc."".add SDWARFLOC size=0
go.info."".add SDWARFINFO size=48
	0x0000 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 01 9c 11 00 00 00 00 00 11 00 00  ................
	0x0020 00 00 00 0e 7e 72 32 00 01 05 00 00 00 00 00 00  ....~r2.........
	rel 1+4 t=28 go.info."".add$abstract+0
	rel 5+8 t=1 "".add+0
	rel 13+8 t=1 "".add+19
	rel 24+4 t=28 go.info."".add$abstract+8
	rel 30+4 t=28 go.info."".add$abstract+16
	rel 42+4 t=28 go.info.int+0
go.range."".add SDWARFRANGE size=0
go.isstmt."".add SDWARFMISC size=0
	0x0000 04 05 01 0e 00                                   .....
go.loc."".main SDWARFLOC size=0
go.info."".main SDWARFINFO size=33
	0x0000 02 22 22 2e 6d 61 69 6e 00 00 00 00 00 00 00 00  ."".main........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 00                                               .
	rel 9+8 t=1 "".main+0
	rel 17+8 t=1 "".main+202
	rel 27+4 t=29 gofile../Users/iceinto/Documents/go/src/github.com/iceopen/golang-extend/demo/asm/x.go+0
go.range."".main SDWARFRANGE size=0
go.isstmt."".main SDWARFMISC size=0
	0x0000 04 13 04 0e 03 03 01 3d 02 03 01 52 02 14 00     .......=...R...
go.loc."".init SDWARFLOC size=0
go.info."".init SDWARFINFO size=33
	0x0000 02 22 22 2e 69 6e 69 74 00 00 00 00 00 00 00 00  ."".init........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 00                                               .
	rel 9+8 t=1 "".init+0
	rel 17+8 t=1 "".init+92
	rel 27+4 t=29 gofile..<autogenerated>+0
go.range."".init SDWARFRANGE size=0
go.isstmt."".init SDWARFMISC size=0
	0x0000 04 0f 04 0c 03 07 01 05 02 09 01 07 02 09 01 15  ................
	0x0010 02 07 00                                         ...
"".statictmp_0 SRODATA size=8
	0x0000 03 00 00 00 00 00 00 00                          ........
"".initdone· SNOPTRBSS size=1
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 00 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 00 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
	0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 bf 03 a8 35 00 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 44+4 t=6 type.*[1]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·7d2d5fca80364273fb07d5820a76fef4 SRODATA dupok size=8
	0x0000 03 00 00 00 00 00 00 00                          ........
gclocals·ef22736e31ca7e9ff10587cea75d17ff SRODATA dupok size=11
	0x0000 03 00 00 00 04 00 00 00 00 08 02                 ...........
gclocals·1cf923758aae2e428391d1783fe59973 SRODATA dupok size=11
	0x0000 03 00 00 00 02 00 00 00 00 01 02                 ...........
